name: Maven Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Checkout Source
        uses: actions/checkout@v4

      # Setup Java 8
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      # Build WAR
      - name: Build Project
        run: mvn clean install -DskipTests

      # Verify WAR
      - name: Verify WAR
        run: |
          ls -lh target
          test -f target/TrainBook-1.0.0-SNAPSHOT.war

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ecrrmk:latest .

      # Tag image
      - name: Tag Docker Image
        run: |
          docker tag ecrrmk:latest \
            ${{ steps.login-ecr.outputs.registry }}/ecrrmk:latest

      # Push image
      - name: Push Docker Image to ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/ecrrmk:latest